- name: Install Nginx on web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Update package cache (Amazon Linux / RHEL family)
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Ensure nginx is installed (Amazon Linux)
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Hello from Terraform + Ansible demo</h1>\nInstance: {{ ansible_facts['nodename'] }}"
        mode: '0644'
